# FOR INTIGER DATA WE USE int KEYWOARD 
a = 24 # this is an integer value and its class is int in python 

# FOR FLOAT DATA WE USE THE float DEYWOARD 
x = 35.6 # THIS IS A FLOAT DATA TYPE IN PYTHON 
# they are decimal numbers 

# STRING DATA TYPE 
# ANYTHING WRITTEN IN THE SINGLE , DOUBLE OR EVEN TRIPLE QUOTES CONDIDERD AS THE STRING 
b = "string 46  45633 2R" # THIS IS STRING DATA TYPE 
print (b)

# BOOLEAN data type 
# this data type can only hold the "True" and "False"
# this is also reserved keywoard in python , such as 
c = True
d = False
# they are boolean values and can be written as bool.


